config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div id="page-content">

</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center" id="color">
      <small>Copyright &copy; Tinder Clone</small>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<div id="nav" class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <img class="logo">
  <h5 class="my-0 mr-md-auto font-weight-normal">Tinder clone</h5>
  <%if account_signed_in? %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to '<a class="text-dark mr-3">Browse</a>'.html_safe, "#"%>
      <%= link_to '<a class="text-dark mr-3">My mathes</a>'.html_safe, "#"%>
      <%= link_to '<a class="text-dark mr-3">Settings</a>'.html_safe, "#"%>
    </nav>

    <%= link_to '<button class="btn btn-link">Sign out</button>'.html_safe, destroy_account_session_path, method: :delete%>

    <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#">Features</a>
      <a class="p-2 text-dark" href="#">Support</a>
      <a class="p-2 text-dark" href="#">Pricing</a>
    </nav>

    <%= link_to '<button class="btn btn-primary">Sign up</button>'.html_safe, new_account_registration_path%>
    <%= link_to '<button class="btn btn-link">Sign in</button>'.html_safe, new_account_session_path%>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinderClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>